import express from 'express';
import multer from 'multer';
import { submitAdvisor, submitCareerApplication, submitContact, submitPartnership } from '../controllers/submissionController.js';
const router=express.Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>{const allowed=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(file.mimetype);cb(allowed?null:new Error('Only PDF, DOC, or DOCX résumés are allowed.'),allowed);}});
router.post('/contact',submitContact);
router.post('/advisor',submitAdvisor);
router.post('/partnership',submitPartnership);
router.post('/career',upload.single('resume'),submitCareerApplication);
export default router;
