import mongoose from 'mongoose';

const gallerySchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
    },
    description: {
      type: String,
      trim: true,
      default: '',
    },
    category: {
      type: String,
      trim: true,
      default: 'General',
    },
    mediaType: {
      type: String,
      enum: ['image', 'video'],
      required: [true, 'Media type is required'],
    },
    sourceType: {
      type: String,
      enum: ['upload', 'url'],
      required: [true, 'Source type is required'],
    },
    mediaUrl: {
      type: String,
      required: [true, 'Media URL is required'],
    },
    // For videos: auto-generated by Cloudinary when uploaded directly,
    // left blank for pasted external URLs (frontend renders a default play-icon card instead).
    thumbnailUrl: {
      type: String,
      default: '',
    },
    // Cloudinary public_id — only set when sourceType is 'upload'. Needed so we can
    // delete the actual file from Cloudinary when the gallery item is removed/replaced.
    publicId: {
      type: String,
      default: '',
    },
  },
  { timestamps: true }
);

export default mongoose.model('Gallery', gallerySchema);